[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "v4-periphery/=lib/v4-periphery/",
    "v4-core/=lib/v4-core/"
]
